# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rtcplayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for rtcplayer
  pod 'GoogleWebRTC'
  pod 'AFNetworking'
end

target 'rtcplayer-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rtcplayer-ios

end
